# GNU General Public License v3.0
# Copyright 2024 Xin Huang
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, please see 
#
#    https://www.gnu.org/licenses/gpl-3.0.en.html


import os
import numpy as np


##### Configs #####


dataset = config["dataset"]


##### Target rules #####

rule all:
    input:
        #"results/1KG/data/.downloaded",
        #expand("resources/annovar/humandb/{refgene}_{database}.txt",
        #       refgene=["hg19", "hg38"], database=["avsnp150", "dbnsfp42c"])
        expand("results/{dataset}/exonic_data/ALL.{mut_type}.vcf.gz",
               dataset=dataset, mut_type=["synonymous", "nonsynonymous"])
        #expand("results/exonic_data/ALL.{mut_type}.vcf.gz", mut_type=['synonymous', 'nonsynonymous']),


##### Modules #####


include: "rules/download.smk"
include: "rules/annovar.smk"
#include: "rules/dfes.smk"
#include: "rules/plots.smk"
