# GNU General Public License v3.0
# Copyright 2024 Xin Huang
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, please see 
#
#    https://www.gnu.org/licenses/gpl-3.0.en.html


import os
import numpy as np


##### Configs #####


dataset = config["dataset"]
chr_num = config["chr_num"]
input_prefix = config["input_prefix"]
input_extension = config["input_extension"]
output_prefix = config["output_prefix"]
ref_gene = config["ref_gene"]

chr_name_list = [c+1 for c in range(chr_num)]


def get_input_vcf(wildcards):
    return os.path.join(
        "results/{dataset}/data/",
        f"{input_prefix}.chr{wildcards.chr_name}.{input_extension}"
    )


##### Target rules #####

rule all:
    input:
        #expand("results/{dataset}/biallelic_snps/{output_prefix}.chr{chr_name}.vcf.gz",
        #       dataset=dataset, output_prefix=output_prefix, chr_name=chr_name_list),
        expand("results/{dataset}/annotated_snps/{output_prefix}.chr{chr_name}.annotated.biallelic.snps.{ref_gene}_multianno.vcf.gz",
               dataset=dataset, output_prefix=output_prefix, chr_name=chr_name_list, ref_gene=ref_gene)
        #expand("results/{dataset}/exonic_data/{output_prefix}.{ref_gene}.{mut_type}.vcf.gz",
        #       dataset=dataset, output_prefix=output_prefix, ref_gene=ref_gene,
        #       mut_type=["synonymous", "nonsynonymous"])


##### Modules #####


include: "rules/download.smk"
include: "rules/annovar.smk"
#include: "rules/dfes.smk"
#include: "rules/plots.smk"
