name: dadi-cli-analysis
channels:
        - conda-forge
dependencies:
        - bcftools
        - dadi-cli
        - matplotlib
        - nlopt
        - numpy
        - pandas
        - pip
        - python==3.9
        - scipy
        - snakemake==7.25.0
        - pip:
                - dadi>2.1.0
