cluster:
        sbatch
                --cpus-per-task={resources.cpus}
                --mem={resources.mem_gb}G
                --time={resources.time}
                --job-name=smk-{rule}-{wildcards}
                --output={log}.out
default-resources:
        - time=1440
        - mem_gb=10
        - cpus=1
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 180
jobs: 200
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
